- hosts: vm2
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install setuptools
      apt:
        name: python3-setuptools
        state: present

    - name: Install Git 
      apt:
        name: git
        state: present 
        update_cache: yes        

    - name: Clone the application repository
      git:
        repo: https://github.com/iamgabs/gestaodeconfiguracao2.git
        dest: /app
        version: HEAD

    - name: Install Python dependencies
      pip:
        requirements: /app/requirements.txt
