name: On commit

on:
  push:
    branches:
      - dev
      - hml
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout e troca de branch 
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.ref }}
       
      - name: Setup ambiente python 
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9 

      - name: Instalando dependencias 
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Executando testes
        run: pytest
